DROP TABLE IF EXISTS TB_MINICURSO_HORARIO_DISPONIVEL;
DROP TABLE IF EXISTS TB_HORARIO_DISPONIVEL;
DROP TABLE IF EXISTS TB_MINISTRANTE;
DROP TABLE IF EXISTS TB_MINICURSO;
DROP TABLE IF EXISTS TB_EVENTO;
DROP TABLE IF EXISTS TB_USUARIO;
DROP TABLE IF EXISTS TB_PERFIL_USUARIO;


CREATE TABLE TB_PERFIL_USUARIO (
	id INT PRIMARY KEY,
	perfil VARCHAR(60)
);

CREATE TABLE TB_USUARIO (
	id INT PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(60),
	email VARCHAR(50) UNIQUE,
	senha VARCHAR(20),
	perfil_id INT,
	FOREIGN KEY (perfil_id) REFERENCES TB_PERFIL_USUARIO (id)
);


CREATE TABLE TB_EVENTO (
	id INT PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(60)
);

CREATE TABLE TB_MINICURSO (
	id INT PRIMARY KEY AUTO_INCREMENT,
	titulo VARCHAR(100),
	publico_alvo VARCHAR(50),
	resumo TEXT,
	vagas INT,
	carga_horaria INT,
	recursos_didaticos TEXT,
	observacoes TEXT,
	evento_id INT,
	usuario_id INT,
	FOREIGN KEY (evento_id) REFERENCES TB_EVENTO (id),
	FOREIGN KEY (usuario_id) REFERENCES TB_USUARIO (id)
);

CREATE TABLE TB_MINISTRANTE (
	id int PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(60),
	email VARCHAR(60),
	titulacao VARCHAR(30),
	biodata TEXT,
	minicurso_id INT,
	FOREIGN KEY (minicurso_id) REFERENCES TB_MINICURSO (id)
);


CREATE TABLE TB_HORARIO_DISPONIVEL (
	id int PRIMARY KEY AUTO_INCREMENT,
	descricao VARCHAR(60)
);

CREATE TABLE TB_MINICURSO_HORARIO_DISPONIVEL (
	minicurso_id int,
	horario_disponivel_id int,
	PRIMARY KEY (minicurso_id, horario_disponivel_id),
	FOREIGN KEY (minicurso_id) REFERENCES TB_MINICURSO (id),
	FOREIGN KEY (horario_disponivel_id) REFERENCES TB_HORARIO_DISPONIVEL (id)
);

INSERT INTO TB_PERFIL_USUARIO VALUES (1,'administrador');
INSERT INTO TB_PERFIL_USUARIO VALUES (2,'organizador');
INSERT INTO TB_PERFIL_USUARIO VALUES (3,'ministrante');
INSERT INTO TB_PERFIL_USUARIO VALUES (4,'aluno');


INSERT INTO TB_USUARIO VALUES (1, 'Igor','igor@igor.com', 'igor',3);

INSERT INTO TB_HORARIO_DISPONIVEL VALUES (1,'Dia 29 - Manhã');
INSERT INTO TB_HORARIO_DISPONIVEL VALUES (2,'Dia 29 - Tarde');
INSERT INTO TB_HORARIO_DISPONIVEL VALUES (3,'Dia 29 - Noite');
INSERT INTO TB_HORARIO_DISPONIVEL VALUES (4,'Dia 30 - Manhã');
INSERT INTO TB_HORARIO_DISPONIVEL VALUES (5,'Dia 30 - Tarde');
INSERT INTO TB_HORARIO_DISPONIVEL VALUES (6,'Dia 30 - Noite');
INSERT INTO TB_HORARIO_DISPONIVEL VALUES (7,'Dia 31 - Manhã');
INSERT INTO TB_HORARIO_DISPONIVEL VALUES (8,'Dia 31 - Tarde');
INSERT INTO TB_HORARIO_DISPONIVEL VALUES (9,'Dia 31 - Noite');

INSERT INTO TB_EVENTO (nome) VALUES ('Semana Nacional de Tecnologia');
INSERT INTO TB_EVENTO (nome) VALUES ('Semana de Telemática');
INSERT INTO TB_EVENTO (nome) VALUES ('Semana de Licenciatura em Física');
INSERT INTO TB_EVENTO (nome) VALUES ('Semana de Ensino em Matemática');
INSERT INTO TB_EVENTO (nome) VALUES ('Semana de Petróleo e Gás');
INSERT INTO TB_EVENTO (nome) VALUES ('Semana de Construção de Edifícios');
INSERT INTO TB_EVENTO (nome) VALUES ('MINIEXPO');

